repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: .*\.(js|mjs|ts|tsx|yml|yaml|css)

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: "v8.12.0"
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]s?$
